### ISSUE TITLE
Include `preferred-versions` in index file

### ISSUE THREAD

**Issue by magthe** [fpco/hackage-mirror#3]
The index file on Hackage contains a file called `preferred-versions` containing information on deprecated versions of packages (e.g. it's where the information that `stack` versin 9.9.9 is deprecated is found).  It'd probably be good to include that file also in the index file on the mirror.

**Comment by snoyberg** [comment]
@dysinger As the last guy to touch this: do you know offhand if this is easy to implement?

**Comment by snoyberg** [comment]
Looking at the codebase myself right now... I don't understand why it needs to reconstruct the tarball instead of just uploading the original, unmodified tarball. This seems to be fragile and CPU-intensive for no reason. @manny-fp @dysinger any thoughts?

**Comment by manny-fp** [comment]
I don't know why.  That repacking code just seems to exist to explicitly leave out `preferred-versions`, but no idea why.  I went back to the original history of simple-mirror in the private repo and the code was there from the beginning.

**Comment by snoyberg** [comment]
In that case, I'm going to modify this to just upload the unmodified file.

**Comment by snoyberg** [comment]
This is now resolved. @magthe if there are still problems, please let me know.
