### ISSUE TITLE
Fails to build with latest version of packages

### ISSUE THREAD

**Issue by ndmitchell** [fpco/hackage-mirror#7]
Using `cabal` I got:

```
[1 of 1] Compiling Hackage.Mirror   ( src\Hackage\Mirror.hs, dist\build\Hackage\Mirror.o )

src\Hackage\Mirror.hs:74:7: error:
    Module `Control.Monad.Trans.Resource' does not export `monadThrow'
   |
74 |       monadThrow,
   |       ^^^^^^^^^^

src\Hackage\Mirror.hs:81:38: error:
    Module `Data.Conduit' does not export `unwrapResumable'
   |
81 | import Data.Conduit ( Source, yield, unwrapResumable, ($=), ($$) )
   |                                      ^^^^^^^^^^^^^^^
```

**Comment by snoyberg** [comment]
This repo is no longer being used, we should probably explicitly deprecate
it. With Hackage Security out, we can't really safely use this. Hebert's
hackage-mirror-tool is currently powering the FP Complete mirror of Hackage.

**Comment by ndmitchell** [comment]
Thanks for the info, that would be very valuable to write on the front page so whoever comes next doesn't make the mistake of trying it.

Thanks for the pointer to the other tool, however, that tool is:

* Not on Hackage
* Uses new cabal-install features that mean I have to go upgrade my Cabal tool
* Requires C Bits I don't have on my system, and because I use Windows, have a pretty solid chance of not working (they certainly didn't on my first go)
* Isn't clear if it can mirror to a directory anyway

I think I'll just go write my own tool...

**Comment by snoyberg** [comment]
I don't know what your exact goals are, but the new Pantry code has the ability to back up all of Hackage to an SQLite database.

**Comment by ndmitchell** [comment]
Thanks! I really just wanted to do some source analysis on all of Hackage, so I may just mess around with curl

**Comment by ndmitchell** [comment]
https://neilmitchell.blogspot.com/2018/11/downloading-all-of-hackage.html - turned out writing a script to download all of Hackage that I cared about is pretty easy.
